#
# General / Lights
#
- alias: 'Lights on in the morning on weekdays'
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '06:45:00'
  condition:
    condition: and
    conditions:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: device_tracker.rolf_5t
      state: 'home'
  action:
    service: scene.turn_on
    entity_id: scene.morning

- alias: 'Lights off in the morning on weekdays'
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '08:45'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: 'Lights off at night'
  initial_state: True
  hide_entity: False
  trigger:
    platform: time
    at: '23:30:00'
  action:
    service: scene.turn_on
    entity_id: scene.all_off

- alias: 'Lights off at sunrise'
  initial_state: True
  hide_entity: False
  trigger:
    platform: sun
    event: sunrise
  action: 
    service: scene.turn_on
    entity_id: scene.all_off

- alias: 'Doorbell'
  trigger:
    platform: mqtt
    topic: hass/doorbell
    payload: ding
  action:
    - service: xiaomi_aqara.play_ringtone
      data:
        gw_mac: 34:ce:00:85:3d:aa
        ringtone_id: '10'
        ringtone_vol: '40'
    # - service: light.turn_on
    #   data:
    #     entity_id: light.lamp_1
    #     rgb_color: [27,94,209]
    - service: light.turn_on
      data:
        entity_id: light.lamp_2
        rgb_color: [27,94,209]
    - delay:
        seconds: 3
    # - service: light.turn_on
    #   data:
    #     entity_id: light.lamp_1
    #     rgb_color: [255,183,123]
    #     brightness: 155
    - service: light.turn_on
      data:
        entity_id: light.lamp_2
        rgb_color: [255,183,123]
        brightness: 155
    - service: xiaomi_aqara.stop_ringtone
      data:
        gw_mac: 34:ce:00:85:3d:aa

#
# Motion
#
- alias: 'Hallway light motion'
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00016da08b
    to: 'on'
    from: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: sun.sun
        state: below_horizon
      - condition: time
        after: '06:30:00'
        before: '23:29:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.lamp_2
        rgb_color: [255,183,123]
        brightness: 125
        transition: True

- alias: 'Hallway light motion at night'
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00016da08b
    to: 'on'
    from: 'off'
  condition:
    condition: time
    after: '23:30:00'
    before: '06:29:00'
  action:
    - service: scene.turn_on
      entity_id: scene.gang_nacht

- alias: 'Turn off hallway light after minute of no motion'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00016da08b
    to: 'off'
    from: 'on'
    for:
      minutes: 2
  action:
    service: light.turn_off
    data:
      entity_id: light.lamp_2
      transition: True

- alias: 'Upstairs hallway light'
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00012299b7
    to: 'on'
    from: 'off'
  condition:
    condition: time
    after: '06:30:00'
    before: '23:29:00'
  action:
    - service: scene.turn_on
      entity_id: scene.overloop

- alias: 'Upstairs hallway light at night'
  initial_state: True
  hide_entity: False
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00012299b7
    to: 'on'
    from: 'off'
  condition:
    condition: time
    after: '23:30:00'
    before: '06:29:00'
  action:
    - service: scene.turn_on
      entity_id: scene.overloop_nacht

- alias: 'Turn off upstairs hallway light after minute of no motion'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_sensor_158d00012299b7
    to: 'off'
    from: 'on'
    for:
      minutes: 2
  action:
    service: light.turn_off
    data:
      entity_id: light.overloop
      transition: True

#
# Switches
#
- alias: 'Living room switch on'
  initial_state: True
  hide_entity: False
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a2f278
      click_type: single
  action:
    - service: scene.turn_on
      entity_id: scene.living_room_on

- alias: 'Living room switch off'
  initial_state: True
  hide_entity: False
  trigger:
    platform: event
    event_type: click
    event_data:
      entity_id: binary_sensor.switch_158d0001a2f278
      click_type: double
  action:
    - service: scene.turn_on
      entity_id: scene.ground_floor_off

#
# Media
#
- alias: 'Dim lights when plex plays on living room'
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: media_player.tv_ue55f8000
      to: 'playing'
      from: 'paused'
    - platform: state
      entity_id: media_player.tv_ue55f8000
      to: 'playing'
      from: 'idle'
  action:
    service: scene.turn_on
    entity_id: scene.evening_plex

- alias: 'When plex is paused turn lights on'
  initial_state: True
  hide_entity: False
  trigger:
    - platform: state
      entity_id: media_player.tv_ue55f8000
      to: 'paused'
      from: 'playing'
    - platform: state
      entity_id: media_player.tv_ue55f8000
      to: 'idle'
      from: 'playing'
  action:
    service: scene.turn_on
    entity_id: scene.living_room_on

#
# Zone based
#
- alias: 'Turn off computer when leave home area'
  initial_state: True
  hide_entity: False
  trigger:
    platform: zone
    event: leave
    zone: zone.home
    entity_id: device_tracker.rolf_5t
  condition:
    condition: state
    entity_id: switch.rolfcomputer
    state: 'on'
  action:
    - service: shell_command.turn_off_rolf_computer
      data:
        user: !secret rolf_computer_user
        ip: !secret rolf_computer_ip
        cmd: !secret rolf_computer_cmd
    - service: notify.pushover
      data_template:
        title: "Turned off computer"
        message: "Left home area computer turned off"

    