- platform: command_line
  switches:
    playstation4:
      command_on: 'ps4-waker -t 15'
      command_off: 'ps4-waker standby'
      command_state: !secret ps4_command
      value_template: '{{ value ==  "0" }}'