- platform: command_line
  switches:
    playstation4:
      command_on: 'ps4-waker -t 15'
      command_off: 'ps4-waker standby'
      command_state: 'nc -z -w 15 192.168.2.66 9295; echo $?'
      value_template: '{{ value ==  "0" }}'