- alias: 'Send telegram notification when leave home area to turn off pc'
  initial_state: True
  hide_entity: False
  trigger:
    platform: zone
    event: leave
    zone: zone.home
    entity_id: device_tracker.rolf_5t
  condition:
    condition: state
    entity_id: switch.rolfcomputer
    state: 'on'
  action:
    - service: telegram_bot.send_message
      data_template:
        title: 'Computer uitzetten?'
        target: !secret telegram_rolf_id
        message: 'Je bent ver van huis, zal ik je computer uit doen?'
        disable_notification: false
        inline_keyboard:
          - "Ja:/pc_turn_off_yes"
          - "Nee:/pc_turn_off_no"

- alias: 'Turn of PC'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/pc_turn_off_yes'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Oke, ik zet hem uit!'
    - service: telegram_bot.edit_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.user_id }}'
        title: 'Computer uitzetten?'
        message: 'Oke, Computer **uitgezet**.' 
    - service: shell_command.turn_off_rolf_computer
      data:
        user: !secret rolf_computer_user
        ip: !secret rolf_computer_ip
        cmd: !secret rolf_computer_cmd

- alias: 'Keep PC on'
  hide_entity: true
  trigger:
    platform: event
    event_type: telegram_callback
    event_data:
      data: '/pc_turn_off_no'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'Oke, hij blijft aan.'
    - service: telegram_bot.edit_message
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.user_id }}'
        title: 'Computer uitzetten?'
        message: 'Oke, Computer blijft **aan**.'